package org.example;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lab2_data_prototest.proto

public final class Lab2DataPrototest {
  private Lab2DataPrototest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TopTenMoviesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TopTenMoviesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmptyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmptyRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031lab2_data_prototest.proto\"G\n\024TopTenMov" +
      "iesResponse\022\014\n\004name\030\001 \003(\t\022\023\n\013description" +
      "\030\002 \003(\t\022\014\n\004rate\030\003 \003(\002\"\016\n\014EmptyRequest2H\n\r" +
      "TopTenService\0227\n\017getTopTenMovies\022\r.Empty" +
      "Request\032\025.TopTenMoviesResponseB\002P\001b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_TopTenMoviesResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TopTenMoviesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TopTenMoviesResponse_descriptor,
        new java.lang.String[] { "Name", "Description", "Rate", });
    internal_static_EmptyRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_EmptyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmptyRequest_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
