package org.example;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lab2_data_prototest.proto

public interface TopTenMoviesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.TopTenMoviesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string name = 1;</code>
   */
  java.util.List<java.lang.String>
      getNameList();
  /**
   * <code>repeated string name = 1;</code>
   */
  int getNameCount();
  /**
   * <code>repeated string name = 1;</code>
   */
  java.lang.String getName(int index);
  /**
   * <code>repeated string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes(int index);

  /**
   * <code>repeated string description = 2;</code>
   */
  java.util.List<java.lang.String>
      getDescriptionList();
  /**
   * <code>repeated string description = 2;</code>
   */
  int getDescriptionCount();
  /**
   * <code>repeated string description = 2;</code>
   */
  java.lang.String getDescription(int index);
  /**
   * <code>repeated string description = 2;</code>
   */
  com.google.protobuf.ByteString
      getDescriptionBytes(int index);

  /**
   * <code>repeated float rate = 3;</code>
   */
  java.util.List<java.lang.Float> getRateList();
  /**
   * <code>repeated float rate = 3;</code>
   */
  int getRateCount();
  /**
   * <code>repeated float rate = 3;</code>
   */
  float getRate(int index);
}
