package com.moviecatalogservice.resources;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lab2_data_prototest.proto

public interface EmptyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.EmptyRequest)
    com.google.protobuf.MessageOrBuilder {
}
