package com.moviecatalogservice.resources;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lab2_data_prototest.proto

/**
 * Protobuf type {@code org.example.TopTenMoviesResponse}
 */
public  final class TopTenMoviesResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.example.TopTenMoviesResponse)
        TopTenMoviesResponseOrBuilder {
  // Use org.example.TopTenMoviesResponse.newBuilder() to construct.
  private TopTenMoviesResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TopTenMoviesResponse() {
    name_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    description_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    rate_ = java.util.Collections.emptyList();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private TopTenMoviesResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              name_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            name_.add(s);
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              description_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000002;
            }
            description_.add(s);
            break;
          }
          case 29: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              rate_ = new java.util.ArrayList<Float>();
              mutable_bitField0_ |= 0x00000004;
            }
            rate_.add(input.readFloat());
            break;
          }
          case 26: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
              rate_ = new java.util.ArrayList<Float>();
              mutable_bitField0_ |= 0x00000004;
            }
            while (input.getBytesUntilLimit() > 0) {
              rate_.add(input.readFloat());
            }
            input.popLimit(limit);
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        name_ = name_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        description_ = description_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        rate_ = java.util.Collections.unmodifiableList(rate_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Lab2DataPrototest.internal_static_TopTenMoviesResponse_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Lab2DataPrototest.internal_static_TopTenMoviesResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            TopTenMoviesResponse.class, Builder.class);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList name_;
  /**
   * <code>repeated string name = 1;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getNameList() {
    return name_;
  }
  /**
   * <code>repeated string name = 1;</code>
   */
  public int getNameCount() {
    return name_.size();
  }
  /**
   * <code>repeated string name = 1;</code>
   */
  public String getName(int index) {
    return name_.get(index);
  }
  /**
   * <code>repeated string name = 1;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes(int index) {
    return name_.getByteString(index);
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 2;
  private com.google.protobuf.LazyStringList description_;
  /**
   * <code>repeated string description = 2;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getDescriptionList() {
    return description_;
  }
  /**
   * <code>repeated string description = 2;</code>
   */
  public int getDescriptionCount() {
    return description_.size();
  }
  /**
   * <code>repeated string description = 2;</code>
   */
  public String getDescription(int index) {
    return description_.get(index);
  }
  /**
   * <code>repeated string description = 2;</code>
   */
  public com.google.protobuf.ByteString
      getDescriptionBytes(int index) {
    return description_.getByteString(index);
  }

  public static final int RATE_FIELD_NUMBER = 3;
  private java.util.List<Float> rate_;
  /**
   * <code>repeated float rate = 3;</code>
   */
  public java.util.List<Float>
      getRateList() {
    return rate_;
  }
  /**
   * <code>repeated float rate = 3;</code>
   */
  public int getRateCount() {
    return rate_.size();
  }
  /**
   * <code>repeated float rate = 3;</code>
   */
  public float getRate(int index) {
    return rate_.get(index);
  }
  private int rateMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    for (int i = 0; i < name_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_.getRaw(i));
    }
    for (int i = 0; i < description_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, description_.getRaw(i));
    }
    if (getRateList().size() > 0) {
      output.writeUInt32NoTag(26);
      output.writeUInt32NoTag(rateMemoizedSerializedSize);
    }
    for (int i = 0; i < rate_.size(); i++) {
      output.writeFloatNoTag(rate_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < name_.size(); i++) {
        dataSize += computeStringSizeNoTag(name_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getNameList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < description_.size(); i++) {
        dataSize += computeStringSizeNoTag(description_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getDescriptionList().size();
    }
    {
      int dataSize = 0;
      dataSize = 4 * getRateList().size();
      size += dataSize;
      if (!getRateList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      rateMemoizedSerializedSize = dataSize;
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof TopTenMoviesResponse)) {
      return super.equals(obj);
    }
    TopTenMoviesResponse other = (TopTenMoviesResponse) obj;

    boolean result = true;
    result = result && getNameList()
        .equals(other.getNameList());
    result = result && getDescriptionList()
        .equals(other.getDescriptionList());
    result = result && getRateList()
        .equals(other.getRateList());
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getNameCount() > 0) {
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getNameList().hashCode();
    }
    if (getDescriptionCount() > 0) {
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescriptionList().hashCode();
    }
    if (getRateCount() > 0) {
      hash = (37 * hash) + RATE_FIELD_NUMBER;
      hash = (53 * hash) + getRateList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static TopTenMoviesResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TopTenMoviesResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TopTenMoviesResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TopTenMoviesResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TopTenMoviesResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TopTenMoviesResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TopTenMoviesResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static TopTenMoviesResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static TopTenMoviesResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static TopTenMoviesResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static TopTenMoviesResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static TopTenMoviesResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(TopTenMoviesResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.example.TopTenMoviesResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.example.TopTenMoviesResponse)
          TopTenMoviesResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Lab2DataPrototest.internal_static_TopTenMoviesResponse_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Lab2DataPrototest.internal_static_TopTenMoviesResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TopTenMoviesResponse.class, Builder.class);
    }

    // Construct using org.example.TopTenMoviesResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      name_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      description_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      rate_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Lab2DataPrototest.internal_static_TopTenMoviesResponse_descriptor;
    }

    public TopTenMoviesResponse getDefaultInstanceForType() {
      return TopTenMoviesResponse.getDefaultInstance();
    }

    public TopTenMoviesResponse build() {
      TopTenMoviesResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public TopTenMoviesResponse buildPartial() {
      TopTenMoviesResponse result = new TopTenMoviesResponse(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        name_ = name_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.name_ = name_;
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        description_ = description_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.description_ = description_;
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        rate_ = java.util.Collections.unmodifiableList(rate_);
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.rate_ = rate_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof TopTenMoviesResponse) {
        return mergeFrom((TopTenMoviesResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(TopTenMoviesResponse other) {
      if (other == TopTenMoviesResponse.getDefaultInstance()) return this;
      if (!other.name_.isEmpty()) {
        if (name_.isEmpty()) {
          name_ = other.name_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureNameIsMutable();
          name_.addAll(other.name_);
        }
        onChanged();
      }
      if (!other.description_.isEmpty()) {
        if (description_.isEmpty()) {
          description_ = other.description_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureDescriptionIsMutable();
          description_.addAll(other.description_);
        }
        onChanged();
      }
      if (!other.rate_.isEmpty()) {
        if (rate_.isEmpty()) {
          rate_ = other.rate_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensureRateIsMutable();
          rate_.addAll(other.rate_);
        }
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      TopTenMoviesResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (TopTenMoviesResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList name_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureNameIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        name_ = new com.google.protobuf.LazyStringArrayList(name_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string name = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getNameList() {
      return name_.getUnmodifiableView();
    }
    /**
     * <code>repeated string name = 1;</code>
     */
    public int getNameCount() {
      return name_.size();
    }
    /**
     * <code>repeated string name = 1;</code>
     */
    public String getName(int index) {
      return name_.get(index);
    }
    /**
     * <code>repeated string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes(int index) {
      return name_.getByteString(index);
    }
    /**
     * <code>repeated string name = 1;</code>
     */
    public Builder setName(
        int index, String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureNameIsMutable();
      name_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string name = 1;</code>
     */
    public Builder addName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureNameIsMutable();
      name_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string name = 1;</code>
     */
    public Builder addAllName(
        Iterable<String> values) {
      ensureNameIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, name_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string name = 1;</code>
     */
    public Builder clearName() {
      name_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string name = 1;</code>
     */
    public Builder addNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureNameIsMutable();
      name_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList description_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureDescriptionIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        description_ = new com.google.protobuf.LazyStringArrayList(description_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <code>repeated string description = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getDescriptionList() {
      return description_.getUnmodifiableView();
    }
    /**
     * <code>repeated string description = 2;</code>
     */
    public int getDescriptionCount() {
      return description_.size();
    }
    /**
     * <code>repeated string description = 2;</code>
     */
    public String getDescription(int index) {
      return description_.get(index);
    }
    /**
     * <code>repeated string description = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes(int index) {
      return description_.getByteString(index);
    }
    /**
     * <code>repeated string description = 2;</code>
     */
    public Builder setDescription(
        int index, String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureDescriptionIsMutable();
      description_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string description = 2;</code>
     */
    public Builder addDescription(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureDescriptionIsMutable();
      description_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string description = 2;</code>
     */
    public Builder addAllDescription(
        Iterable<String> values) {
      ensureDescriptionIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, description_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string description = 2;</code>
     */
    public Builder clearDescription() {
      description_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string description = 2;</code>
     */
    public Builder addDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureDescriptionIsMutable();
      description_.add(value);
      onChanged();
      return this;
    }

    private java.util.List<Float> rate_ = java.util.Collections.emptyList();
    private void ensureRateIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        rate_ = new java.util.ArrayList<Float>(rate_);
        bitField0_ |= 0x00000004;
       }
    }
    /**
     * <code>repeated float rate = 3;</code>
     */
    public java.util.List<Float>
        getRateList() {
      return java.util.Collections.unmodifiableList(rate_);
    }
    /**
     * <code>repeated float rate = 3;</code>
     */
    public int getRateCount() {
      return rate_.size();
    }
    /**
     * <code>repeated float rate = 3;</code>
     */
    public float getRate(int index) {
      return rate_.get(index);
    }
    /**
     * <code>repeated float rate = 3;</code>
     */
    public Builder setRate(
        int index, float value) {
      ensureRateIsMutable();
      rate_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated float rate = 3;</code>
     */
    public Builder addRate(float value) {
      ensureRateIsMutable();
      rate_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated float rate = 3;</code>
     */
    public Builder addAllRate(
        Iterable<? extends Float> values) {
      ensureRateIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, rate_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated float rate = 3;</code>
     */
    public Builder clearRate() {
      rate_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:org.example.TopTenMoviesResponse)
  }

  // @@protoc_insertion_point(class_scope:org.example.TopTenMoviesResponse)
  private static final TopTenMoviesResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new TopTenMoviesResponse();
  }

  public static TopTenMoviesResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TopTenMoviesResponse>
      PARSER = new com.google.protobuf.AbstractParser<TopTenMoviesResponse>() {
    public TopTenMoviesResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new TopTenMoviesResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TopTenMoviesResponse> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<TopTenMoviesResponse> getParserForType() {
    return PARSER;
  }

  public TopTenMoviesResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

